services:
  php-apache-environment:
    container_name: php-apache-ap
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - 8001:80
  db:
    container_name: dbsap
    image: 'bitnami/mysql:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: APDB
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "3306:3306"